# 1. Push Docker images to an ECR repository

name: Push to Amazon ECR

on:
  push:
    branches: [prod]

jobs:
  
  build:
    name: Build the Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}             # set this to your AWS_ACCESS_KEY_ID secret key in git 
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}     # set this to your AWS_SECRET_ACCESS_KEY secret key in git 
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}             # set this to your AWS_SESSION_TOKEN secret key in git 
        aws-region: us-east-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      #env:
        #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}             # set this to your AWS_ACCESS_KEY_ID secret key in git 
        #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}     # set this to your AWS_SECRET_ACCESS_KEY secret key in git 
        #AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}             # set this to your AWS_SESSION_TOKEN secret key in git 
        #AWS_REGION: us-east-1
        
        
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REPOSITORY: ddogra1-labs-cats           # set this to your Amazon ECR repository name
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}                            
        GIT_SHA: ${{ github.sha }}
        
      run: |
        #### Build a docker container for Cats  push it to ECR
        cd docker/cats/
        ls -ltra
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:CATS_$GIT_SHA .

        #Pushing the Cats Docker Image to ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:CATS_$GIT_SHA

