- name: Run tflint with reviewdog
  # You may pin to the exact commit or the version.
  # uses: reviewdog/action-tflint@86b1913cb664b079cb435014ad64835acf66c639
  uses: reviewdog/action-tflint@v1.16.2
  with:
    # GITHUB_TOKEN
    github_token: # default is ${{ github.token }}
    # Report level for reviewdog [info,warning,error]
    level: # optional, default is error
    # Reporter of reviewdog command [github-pr-check,github-pr-review].
Default is github-pr-check.

    reporter: # optional, default is github-pr-check
    # Filtering for the reviewdog command [added,diff_context,file,nofilter].
Default is added.

    filter_mode: # optional, default is added
    # Exit code for reviewdog when errors are found [true,false]
Default is `false`.

    fail_on_error: # optional, default is false
    # Directory to run the action on, from the repo root.
Default is . ( root of the repository)

    working_directory: # optional, default is .
    # The tflint version to install and use.
Default is to use the latest release version.

    tflint_version: # optional, default is latest
    # Space separated, official (from the terraform-linters GitHub organization) tflint rulesets to install and use. If a pre-configured `TFLINT_PLUGIN_DIR` is set, rulesets are installed in that directory.
Default is empty.

    tflint_rulesets: # optional, default is 
    # Whether or not to run tflint --init prior to running scan [true,false]
Default is `false`.

    tflint_init: # optional, default is false
    # List of arguments to send to tflint
For the output to be parsable by reviewdog --format=checkstyle is enforced
Default is --module.

    flags: # optional, default is --module
